/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\gltf\Model\europ.glb -j -r public 
*/

import { useGLTF } from '@react-three/drei'

export function Europ3(props) {
  const { nodes, materials } = useGLTF('/gltf/Model/europ.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-10.395, -0.6, 2.527]} rotation={[1.583, 0, 0]} scale={0.0003}>
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001.geometry} material={materials['PEINTURE_-_BLANC_TITANIUM.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_1.geometry} material={materials['ENDUIT_-_PLATRE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_2.geometry} material={materials['BRIQUE_-_BLANCHE_NATURELLE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_3.geometry} material={materials['ENDUIT_-_BLANC_NATURE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_4.geometry} material={materials['PEINTURE_-_NOIR.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_5.geometry} material={materials['APPAREILLAGE_-_GRANIT.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_6.geometry} material={materials['TRANSP__-_VERRE_CLAIR__RAPIDE_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_7.geometry} material={materials['METAL_-_ACIER_INOXYDABLE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_8.geometry} material={materials['METAL_-_ACIER_INOXYDABLE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_9.geometry} material={materials['METAL_-_ACIER_INOXYDABLE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_10.geometry} material={materials['METAL_-_ALUMINIUM_GRIS_FONCE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_11.geometry} material={materials['METAL_-_ALUMINIUM_GRIS_ANTHRAC.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_12.geometry} material={materials['BOIS_-_PIN_GRANULEUX_HORIZONTA.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_13.geometry} material={materials['EI704_EICHE__INTERNORM_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_14.geometry} material={materials['FINE_UPHOLSTERY_LIGHT_BROWN__F.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_15.geometry} material={materials['TOP_FROSTED_GLASS__FORAFORM_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_16.geometry} material={materials['EI703_EICHE__INTERNORM_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_17.geometry} material={materials['PEINTURE_-_BLEU_COBALT.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_18.geometry} material={materials['METAL_-_ALUMINIUM.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_19.geometry} material={materials['METAL_-_ALUMINIUM.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_20.geometry} material={materials['METAL_-_ALUMINIUM.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_21.geometry} material={materials['AIR_-_VIDE_D_AIR.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_22.geometry} material={materials['PLATRE_-_BRIQUES_OU_CARREAUX_D.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_23.geometry} material={materials['METAL_-_ALUMINIUM_ROUGE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_24.geometry} material={materials['OREGON_DECOR__INTERNORM_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_25.geometry} material={materials['MARBRE_-_NOIR.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_26.geometry} material={materials['PEINTURE_-_CARMIN.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_27.geometry} material={materials['ENDUIT_-_JAUNE_NATURE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_28.geometry} material={materials['EDELWEI___INTERNORM_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_29.geometry} material={materials['ENV__-_TERRE_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_30.geometry} material={materials['180M_CREME__RAL1015M__INTERNOR.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_31.geometry} material={materials['EI701_EICHE__INTERNORM_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_32.geometry} material={materials['LAMINATE_WHITE_411__FORAFORM_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_33.geometry} material={materials['EI700_EICHE__INTERNORM_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_34.geometry} material={materials['TRANSP__-_VERRE_BLEUTE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_35.geometry} material={materials['TRANSP__-_VERRE_VERT.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_36.geometry} material={materials['PEINTURE_-_BLANC_BRILLANT.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_37.geometry} material={materials['HM906__ALUMINIUM__NATUR__INTER.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_38.geometry} material={materials['ROUGH_UPHOLSTERY_SAND__FORAFOR.001']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_39.geometry} material={materials['METAL_-_CHROME.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_40.geometry} material={materials['HM735__HELLGRAU__INTERNORM_.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_41.geometry} material={materials['BEIGE__NCS_S_4005-Y20R___FORAF.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_42.geometry} material={materials['PURPLE__NCS_S_7020-R40B___FORA.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_43.geometry} material={materials['METAL_-_ALUMINIUM_BEIGE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_44.geometry} material={materials['METAL-INOX.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_45.geometry} material={materials['METAL-INOX.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_46.geometry} material={materials['METAL-INOX.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_47.geometry} material={materials['METAL-INOX.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_48.geometry} material={materials['METAL-ALUMINIUM.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_49.geometry} material={materials['METAL-ALUMINIUM.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_50.geometry} material={materials['METAL-ALUMINIUM.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_51.geometry} material={materials['METAL-NICKEL.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_52.geometry} material={materials['METAL-ZINC_COPIE.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_53.geometry} material={materials['METAL-LAITON.002']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023001_54.geometry} material={materials['METAL-ALUMINIUM_3.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/gltf/Model/europ.glb')
